# Generated by Django 5.0.2 on 2024-02-19 15:50

import itau.views
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[itau.views.validate_cpf])),
                ('estado_civil', models.CharField(max_length=20)),
            ],
        ),
    ]
